// Prompt strategy: describe the SCENE/BACKGROUND, not the product.
// The product comes from the input image — Flux Dev preserves it when prompt_strength < 0.65.
// Each prompt ends with a quality anchor to reinforce commercial photography output.

export const PHOTO_SETS = [
  {
    id: "underwear",
    exampleImage: "/images/photo-sets/genel.png",
    labelTR: "İç Giyim Fotoğraf Seti",
    labelEN: "Underwear Photo Set",
    descriptionTR: "Boxer, külot, atlet ve iç giyim için: stüdyo hero, flat lay, kumaş detay, lifestyle, bel detayı ve minimalist e-ticaret.",
    descriptionEN: "For boxer briefs, underwear and innerwear: studio hero, flat lay, fabric detail, lifestyle, waistband detail, minimalist e-commerce.",
    scenes: [
      {
        scene: "studio-white",
        labelTR: "Stüdyo Beyaz Hero",
        labelEN: "Studio White Hero",
        prompt: "pure white seamless paper backdrop, front-facing product display, soft diffused box lighting from both sides, no shadows on background, professional e-commerce catalog photography, high resolution sharp focus",
      },
      {
        scene: "flat-lay-top",
        labelTR: "Flat Lay Üstten",
        labelEN: "Overhead Flat Lay",
        prompt: "overhead top-down flat lay on clean white surface, perfectly centered composition, soft natural window light from the side, no props, minimalist e-commerce photography, shot from directly above",
      },
      {
        scene: "fabric-detail",
        labelTR: "Kumaş ve Bel Detayı",
        labelEN: "Fabric & Waistband Detail",
        prompt: "extreme close-up macro shot of elastic waistband and fabric texture, sharp focus on stitching and material quality, soft studio lighting, white background, textile detail photography",
      },
      {
        scene: "lifestyle-drawer",
        labelTR: "Yaşam Tarzı — Çekmece",
        labelEN: "Lifestyle — Drawer",
        prompt: "neatly folded on a light wooden drawer or bedroom shelf, morning natural daylight, clean bedroom interior context, soft focus background, lifestyle home photography",
      },
      {
        scene: "folded-stack",
        labelTR: "Katlanmış Sunum",
        labelEN: "Folded Presentation",
        prompt: "product neatly folded and stacked on a clean marble or light wood surface, side angle, soft studio lighting, retail presentation style, white or light gray background, commercial product photography",
      },
      {
        scene: "minimal-ecom",
        labelTR: "Minimalist E-Ticaret",
        labelEN: "Minimalist E-Commerce",
        prompt: "clean light gray gradient background, centered product display, soft even lighting with no harsh shadows, ghost mannequin or folded view, minimalist fashion e-commerce photography, crisp high resolution",
      },
    ],
  },
  {
    id: "general",
    exampleImage: "/images/photo-sets/genel.png",
    labelTR: "Genel Ürün Fotoğraf Seti",
    labelEN: "General Product Photo Set",
    descriptionTR: "Her ürün için 6 sahne: stüdyo beyaz, light gray stüdyo, detay yakın, lifestyle bağlam, flat lay ve editöryal.",
    descriptionEN: "6 scenes for any product: studio white, light gray studio, detail closeup, lifestyle context, flat lay, editorial.",
    scenes: [
      {
        scene: "studio-white",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, centered product, soft box studio lighting, no shadows, professional e-commerce product photography, sharp focus, high resolution",
      },
      {
        scene: "studio-gray",
        labelTR: "Stüdyo Gri",
        labelEN: "Studio Gray",
        prompt: "clean light gray seamless background, centered product, soft directional studio lighting, subtle shadow below product, professional catalog photography",
      },
      {
        scene: "detail-closeup",
        labelTR: "Detay Yakın Çekim",
        labelEN: "Detail Closeup",
        prompt: "extreme close-up macro shot of product material and texture, sharp focus, white studio background, professional product detail photography, studio lighting",
      },
      {
        scene: "lifestyle-context",
        labelTR: "Yaşam Tarzı Bağlamı",
        labelEN: "Lifestyle Context",
        prompt: "product placed on a clean wooden surface or white shelf in a minimalist modern interior, natural side light from window, lifestyle product photography, soft blurred background",
      },
      {
        scene: "flat-lay",
        labelTR: "Flat Lay",
        labelEN: "Flat Lay",
        prompt: "overhead flat lay on a clean white or light pastel surface, top-down composition, soft natural lighting, no distracting props, e-commerce flat lay photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "light gray or off-white gradient studio background, single strong directional key light creating subtle shadow, high-end commercial product photography, minimalist editorial style",
      },
    ],
  },
  {
    id: "armchair",
    exampleImage: "/images/photo-sets/koltuk-berjer.png",
    labelTR: "Koltuk & Berjer Fotoğraf Seti",
    labelEN: "Armchair & Bergère Photo Set",
    descriptionTR: "Koltuk ve berjerler için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for armchairs and bergères.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, centered armchair, even soft studio lighting, no shadows, professional furniture e-commerce photography, high resolution front view",
      },
      {
        scene: "living-room",
        labelTR: "Oturma Odası",
        labelEN: "Living Room Setting",
        prompt: "beautifully designed modern living room interior, light wood floor, neutral walls, natural daylight from left window, lifestyle interior photography, slightly blurred background",
      },
      {
        scene: "upholstery-detail",
        labelTR: "Döşeme Detayı",
        labelEN: "Upholstery Detail",
        prompt: "extreme close-up of fabric upholstery texture and stitching, sharp focus on material weave, soft studio side lighting, white background, textile macro photography",
      },
      {
        scene: "cozy-usage",
        labelTR: "Kullanım Sahnesi",
        labelEN: "Usage Scene",
        prompt: "cozy reading corner setting, warm ambient lamp lighting, small side table with book nearby, soft focus blurred background, lifestyle home interior photography",
      },
      {
        scene: "alt-angle",
        labelTR: "45° Açı",
        labelEN: "45° Side Angle",
        prompt: "45-degree three-quarter side angle view, clean neutral light gray background, professional furniture photography showing full silhouette and legs",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "high-end interior design editorial setting, architectural concrete wall or luxury wallpaper background, dramatic side lighting, interior design magazine photography",
      },
    ],
  },
  {
    id: "sofa-set",
    exampleImage: "/images/photo-sets/koltuk-takimi.png",
    labelTR: "Koltuk Takımı Fotoğraf Seti",
    labelEN: "Sofa Set Photo Set",
    descriptionTR: "3+2+1, köşe ve komple oturma grupları için 6 sahne.",
    descriptionEN: "6 scenes for 3+2+1, corner and full seating sets.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless studio backdrop, centered composition, even overhead and side studio lighting, professional furniture catalog photography, high resolution",
      },
      {
        scene: "living-room",
        labelTR: "Geniş Oturma Odası",
        labelEN: "Spacious Living Room",
        prompt: "spacious bright modern living room, light hardwood flooring, large window with natural daylight, minimal decorative accents, full interior lifestyle photography",
      },
      {
        scene: "upholstery-detail",
        labelTR: "Döşeme Detayı",
        labelEN: "Upholstery Detail",
        prompt: "close-up of sofa fabric texture, cushion seam and tufting detail, soft diffused studio lighting, macro textile photography, white background",
      },
      {
        scene: "family",
        labelTR: "Aile Sahnesi",
        labelEN: "Family Scene",
        prompt: "warm living room atmosphere, throw pillows and cozy blanket on sofa, warm ambient lighting, afternoon light, home lifestyle interior photography, no people",
      },
      {
        scene: "configuration",
        labelTR: "Konfigürasyon Görünümü",
        labelEN: "Configuration View",
        prompt: "wide angle architectural interior view showing full sofa set arrangement in a styled living room, natural light, overhead or elevated angle",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "luxury interior design magazine editorial, marble flooring, large window with city view, dramatic side lighting, architectural interior photography",
      },
    ],
  },
  {
    id: "dining-set",
    exampleImage: "/images/photo-sets/yemek-masasi.png",
    labelTR: "Yemek Masası Takımı Fotoğraf Seti",
    labelEN: "Dining Table Set Photo Set",
    descriptionTR: "Yemek masası takımları için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for dining sets.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, centered dining set, professional studio lighting, furniture product photography, high resolution",
      },
      {
        scene: "dining-room",
        labelTR: "Yemek Odası",
        labelEN: "Dining Room Setting",
        prompt: "beautifully designed dining room, neutral walls, pendant light above, natural window light, lifestyle interior photography, light wood or marble flooring",
      },
      {
        scene: "table-setting",
        labelTR: "Sofra Düzeni",
        labelEN: "Styled Table Setting",
        prompt: "dining table set with simple white plates, linen napkins and minimal decor, warm ambient lighting, lifestyle dining photography, no people",
      },
      {
        scene: "wood-detail",
        labelTR: "Ahşap Yüzey Detayı",
        labelEN: "Wood Surface Detail",
        prompt: "extreme close-up of dining table wood grain surface texture and edge joinery, sharp focus, soft side studio lighting, macro woodworking detail photography",
      },
      {
        scene: "wide-room",
        labelTR: "Geniş Oda Görünümü",
        labelEN: "Wide Room View",
        prompt: "wide angle architectural interior showing dining set in full room context, natural light, full scale perspective, interior design photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "luxury dining editorial setting, marble or herringbone wood floor, dramatic pendant lighting, high-end interior magazine photography",
      },
    ],
  },
  {
    id: "chair",
    exampleImage: "/images/photo-sets/sandalye.png",
    labelTR: "Sandalye Fotoğraf Seti",
    labelEN: "Chair Photo Set",
    descriptionTR: "Sandalyeler için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for chairs.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, chair centered and front-facing, soft studio lighting, professional furniture e-commerce photography",
      },
      {
        scene: "interior",
        labelTR: "İç Mekan",
        labelEN: "Interior Setting",
        prompt: "minimalist modern interior, light concrete or white wall background, natural side lighting, clean floor, lifestyle furniture photography",
      },
      {
        scene: "material-detail",
        labelTR: "Malzeme Detayı",
        labelEN: "Material Detail",
        prompt: "close-up of chair seat material texture and leg joinery, sharp macro focus, white studio background, soft diffused lighting, furniture detail photography",
      },
      {
        scene: "desk-context",
        labelTR: "Masa Bağlamı",
        labelEN: "Desk Context",
        prompt: "chair at a clean minimal desk, natural window light, work or dining context, lifestyle interior photography, soft blurred background",
      },
      {
        scene: "alt-angle",
        labelTR: "45° Açı",
        labelEN: "45° Angle",
        prompt: "45-degree three-quarter angle, clean light gray background, showing full silhouette and back of chair, professional furniture photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "high-end interior editorial, architectural background, dramatic directional lighting, design magazine photography, minimal composition",
      },
    ],
  },
  {
    id: "bed-frame",
    exampleImage: "/images/photo-sets/karyola.png",
    labelTR: "Karyola Fotoğraf Seti",
    labelEN: "Bed Frame Photo Set",
    descriptionTR: "Karyolalar için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for bed frames.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, bed frame with white bedding, soft studio lighting, furniture product photography, high resolution",
      },
      {
        scene: "bedroom",
        labelTR: "Yatak Odası",
        labelEN: "Bedroom Setting",
        prompt: "bright styled bedroom interior, white or light gray walls, morning natural light from side window, white crisp bedding, lifestyle bedroom photography",
      },
      {
        scene: "headboard-detail",
        labelTR: "Başlık Detayı",
        labelEN: "Headboard Detail",
        prompt: "close-up detail of bed headboard material and construction, sharp focus on texture and stitching, soft studio side lighting, macro furniture detail photography",
      },
      {
        scene: "morning-lifestyle",
        labelTR: "Sabah Sahnesi",
        labelEN: "Morning Lifestyle",
        prompt: "soft morning bedroom atmosphere, rumpled white linen bedding, warm golden morning light, cozy comfortable lifestyle, no people, lifestyle photography",
      },
      {
        scene: "foot-angle",
        labelTR: "Ayak Ucundan Açı",
        labelEN: "Foot-of-Bed Angle",
        prompt: "foot-of-bed perspective showing full headboard and room, wide angle interior photography, styled bedroom context, natural light",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "luxury hotel-style bedroom editorial, crisp white linen, dramatic side lighting, architectural interior photography, high-end bedroom magazine",
      },
    ],
  },
  {
    id: "office-furniture",
    exampleImage: "/images/photo-sets/ofis-mobilyasi.png",
    labelTR: "Ofis Mobilyası Fotoğraf Seti",
    labelEN: "Office Furniture Photo Set",
    descriptionTR: "Ofis mobilyaları için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for office furniture.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, centered product, professional studio lighting, corporate product photography, high resolution",
      },
      {
        scene: "office",
        labelTR: "Modern Ofis",
        labelEN: "Modern Office",
        prompt: "clean modern office interior, neutral light gray walls, natural window light, minimal desk accessories, professional workspace lifestyle photography",
      },
      {
        scene: "surface-detail",
        labelTR: "Yüzey Detayı",
        labelEN: "Surface Detail",
        prompt: "close-up of furniture surface finish and hardware, sharp macro focus, soft studio lighting, material quality detail photography",
      },
      {
        scene: "work-context",
        labelTR: "Çalışma Bağlamı",
        labelEN: "Work Context",
        prompt: "minimal desk setup context, laptop and notebook on surface, natural window light, clean productive workspace, lifestyle office photography, no people",
      },
      {
        scene: "alt-angle",
        labelTR: "Alternatif Açı",
        labelEN: "Alternative Angle",
        prompt: "three-quarter side angle view, clean neutral gray background, showing full furniture profile and dimensions, professional commercial photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "premium executive office editorial, floor-to-ceiling windows, city view background, dramatic architectural lighting, high-end business interior photography",
      },
    ],
  },
  {
    id: "floor-cushion",
    exampleImage: "/images/photo-sets/minder.png",
    labelTR: "Minder Fotoğraf Seti",
    labelEN: "Floor Cushion Photo Set",
    descriptionTR: "Minderler için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for floor cushions.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, cushion centered and upright, soft studio lighting, clean textile product photography",
      },
      {
        scene: "boho-lifestyle",
        labelTR: "Boho Yaşam Tarzı",
        labelEN: "Bohemian Lifestyle",
        prompt: "warm bohemian living room floor, woven rug background, warm afternoon natural light, plants in background, lifestyle interior photography",
      },
      {
        scene: "fabric-detail",
        labelTR: "Kumaş Detayı",
        labelEN: "Fabric Detail",
        prompt: "extreme close-up of cushion fabric weave texture and stitching edges, sharp macro focus, soft studio lighting, white background, textile photography",
      },
      {
        scene: "floor-context",
        labelTR: "Zemin Bağlamı",
        labelEN: "Floor Context",
        prompt: "clean light wood floor surface, cushion placed naturally, soft diffused natural light from above, minimal cozy interior context, lifestyle photography",
      },
      {
        scene: "group-arrangement",
        labelTR: "Grup Düzeni",
        labelEN: "Group Arrangement",
        prompt: "multiple cushions arranged together on a clean floor, styled home decor display, natural light, overhead or low angle, interior styling photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "minimalist interior editorial, clean concrete or white plaster wall, single dramatic side light, architectural home decor photography",
      },
    ],
  },
  {
    id: "throw-pillow",
    exampleImage: "/images/photo-sets/kirlent.png",
    labelTR: "Kırlent Fotoğraf Seti",
    labelEN: "Throw Pillow Photo Set",
    descriptionTR: "Kırlentler için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for throw pillows.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, pillow standing upright or flat, soft even studio lighting, clean home textile product photography",
      },
      {
        scene: "sofa-styled",
        labelTR: "Koltuk Üzerinde",
        labelEN: "Styled on Sofa",
        prompt: "neutral light gray or cream sofa background, pillow naturally placed, natural window light, minimalist interior lifestyle photography",
      },
      {
        scene: "fabric-detail",
        labelTR: "Kumaş Detayı",
        labelEN: "Fabric Detail",
        prompt: "extreme close-up macro of pillow fabric weave, embroidery or print pattern detail, sharp focus, soft studio lighting, white background, textile photography",
      },
      {
        scene: "bed-styled",
        labelTR: "Yatak Üzerinde",
        labelEN: "Styled on Bed",
        prompt: "white or neutral bedding background, pillow placed naturally on bed, soft morning light, clean bedroom styling, interior photography",
      },
      {
        scene: "flat-lay",
        labelTR: "Flat Lay",
        labelEN: "Flat Lay",
        prompt: "overhead flat lay on clean white linen surface, pillow centered, soft natural window light, top-down composition, minimal e-commerce photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "high-end interior editorial context, marble or luxury surface, dramatic single side light, luxury home decor magazine photography",
      },
    ],
  },
  {
    id: "curtain",
    exampleImage: "/images/photo-sets/perde.png",
    labelTR: "Perde Fotoğraf Seti",
    labelEN: "Curtain Photo Set",
    descriptionTR: "Perdeler için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for curtains.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Asılı",
        labelEN: "Studio Hanging",
        prompt: "clean white studio background, curtain hung and fully draped showing complete fall, even studio lighting, full length textile product photography",
      },
      {
        scene: "window",
        labelTR: "Pencere Ortamı",
        labelEN: "Window Setting",
        prompt: "elegant window with bright natural daylight, light filtering through sheer fabric, minimalist room interior, airy lifestyle interior photography",
      },
      {
        scene: "fabric-detail",
        labelTR: "Kumaş Döküm Detayı",
        labelEN: "Fabric Drape Detail",
        prompt: "close-up of curtain fabric drape and pleat detail, light filtering through material texture, macro textile photography, soft studio light",
      },
      {
        scene: "full-room",
        labelTR: "Tam Oda Görünümü",
        labelEN: "Full Room Context",
        prompt: "fully styled living room or bedroom showing curtains framing the window, natural daylight, interior design photography, wide angle room view",
      },
      {
        scene: "pattern-detail",
        labelTR: "Desen Detayı",
        labelEN: "Pattern Detail",
        prompt: "close-up flat detail shot of curtain pattern, weave texture or embroidery, sharp focus, neutral background, professional textile photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "luxury interior editorial, dramatic backlit window creating silhouette effect, high-end home magazine photography, architectural light",
      },
    ],
  },
  {
    id: "tablecloth",
    exampleImage: "/images/photo-sets/masa-ortusu.png",
    labelTR: "Masa Örtüsü Fotoğraf Seti",
    labelEN: "Tablecloth Photo Set",
    descriptionTR: "Masa örtüleri için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for tablecloths.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Üstten",
        labelEN: "Studio Top View",
        prompt: "white studio background, tablecloth spread flat on a table, overhead slightly angled view, clean studio lighting, full spread textile product photography",
      },
      {
        scene: "table-setting",
        labelTR: "Minimal Sofra",
        labelEN: "Minimal Table Setting",
        prompt: "dining table with simple white plates and linen napkins, tablecloth fully spread, warm ambient window light, minimal lifestyle dining photography, no people",
      },
      {
        scene: "fabric-detail",
        labelTR: "Kumaş Doku Detayı",
        labelEN: "Fabric Texture Detail",
        prompt: "close-up macro of tablecloth fabric weave texture and hemmed edge, sharp focus, soft studio side lighting, white background, textile photography",
      },
      {
        scene: "outdoor-dining",
        labelTR: "Bahçe Masası",
        labelEN: "Garden Table",
        prompt: "outdoor garden or terrace setting, natural sunlight, green foliage in soft background, lifestyle outdoor dining photography, no people",
      },
      {
        scene: "flat-lay",
        labelTR: "Flat Lay Editöryal",
        labelEN: "Flat Lay Editorial",
        prompt: "overhead flat lay composition, tablecloth on surface with minimal decorative elements, clean top-down photography, natural light, editorial home decor",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "luxury dining editorial, candlelit warm atmosphere, elegant table surface, dramatic moody lighting, high-end interior magazine photography",
      },
    ],
  },
  {
    id: "blanket",
    exampleImage: "/images/photo-sets/battaniye.png",
    labelTR: "Battaniye Fotoğraf Seti",
    labelEN: "Blanket Photo Set",
    descriptionTR: "Battaniyeler için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for blankets.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Hero",
        labelEN: "Studio Hero",
        prompt: "pure white seamless background, blanket neatly folded or draped, soft studio lighting showing texture, clean textile product photography",
      },
      {
        scene: "cozy-sofa",
        labelTR: "Koltukta Dökümlü",
        labelEN: "Draped on Sofa",
        prompt: "neutral cream or gray sofa background, blanket naturally draped over armrest and seat, warm afternoon indoor lighting, cozy home lifestyle photography",
      },
      {
        scene: "fabric-detail",
        labelTR: "Kumaş Doku Detayı",
        labelEN: "Fabric Texture Detail",
        prompt: "extreme close-up of blanket weave or knit texture, showing softness and material quality, sharp macro focus, warm studio lighting, textile photography",
      },
      {
        scene: "bed-foot",
        labelTR: "Yatak Ayak Ucunda",
        labelEN: "Foot of Bed",
        prompt: "white bedding background, blanket folded neatly at foot of bed, soft morning bedroom light, lifestyle bedroom photography, clean interior",
      },
      {
        scene: "basket-fold",
        labelTR: "Sepet veya Raf Düzeni",
        labelEN: "Basket or Shelf Display",
        prompt: "blanket folded and placed in a woven basket or on a wooden shelf, lifestyle home decor photography, warm natural light, interior context",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "moody winter interior editorial, dramatic warm side lighting, dark wood or stone background, luxury home magazine photography",
      },
    ],
  },
  {
    id: "bedspread",
    exampleImage: "/images/photo-sets/yatak-ortusu.png",
    labelTR: "Yatak Örtüsü & Pike Fotoğraf Seti",
    labelEN: "Bedspread & Quilt Photo Set",
    descriptionTR: "Yatak örtüsü ve pikeler için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for bedspreads and quilts.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Yatakta",
        labelEN: "Studio on Bed",
        prompt: "pure white seamless background, bedspread spread neatly on a bed, clean even studio lighting, home textile e-commerce photography",
      },
      {
        scene: "bedroom",
        labelTR: "Yatak Odası",
        labelEN: "Bedroom Setting",
        prompt: "bright styled bedroom, white walls, natural morning window light, bedspread fully covering bed, lifestyle bedroom interior photography",
      },
      {
        scene: "quilt-detail",
        labelTR: "Nakış ve Doku Detayı",
        labelEN: "Quilting Detail",
        prompt: "close-up of bedspread quilting pattern, embroidery or fabric texture, sharp macro focus, soft diffused lighting, white background, textile detail photography",
      },
      {
        scene: "fully-styled",
        labelTR: "Komple Stilize Yatak",
        labelEN: "Fully Styled Bed",
        prompt: "bed fully styled with matching pillows and cushions, bright airy bedroom interior, natural light, complete bedroom lifestyle photography",
      },
      {
        scene: "flat-lay-detail",
        labelTR: "Flat Lay Detay",
        labelEN: "Flat Lay Detail",
        prompt: "overhead flat lay close-up of bedspread texture and pattern, top-down composition, soft natural light, editorial textile photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "luxury hotel bedroom editorial, pristine white linen, dramatic soft side lighting, architectural interior photography, premium bedding magazine",
      },
    ],
  },
  {
    id: "baby-clothing",
    exampleImage: "/images/photo-sets/bebek-kiyafeti.png",
    labelTR: "Bebek Kıyafeti Fotoğraf Seti",
    labelEN: "Baby Clothing Photo Set",
    descriptionTR: "Bebek kıyafetleri için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for baby clothing.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, clothing flat or ghost mannequin display, soft even studio lighting, clean e-commerce apparel photography",
      },
      {
        scene: "flat-lay-props",
        labelTR: "Aksesuvarlı Flat Lay",
        labelEN: "Flat Lay with Props",
        prompt: "overhead flat lay on soft pastel pink or mint background, small wooden toys and baby shoes as props, natural window light, baby lifestyle product photography",
      },
      {
        scene: "fabric-detail",
        labelTR: "Kumaş Yumuşaklık Detayı",
        labelEN: "Fabric Softness Detail",
        prompt: "extreme close-up of baby clothing fabric texture and stitching, showing softness and quality, macro photography, white studio background, soft lighting",
      },
      {
        scene: "nursery-hanger",
        labelTR: "Bebek Odası Askısı",
        labelEN: "Nursery Hanger",
        prompt: "small wooden decorative hanger in a soft nursery setting, pastel background, natural light, lifestyle baby product photography",
      },
      {
        scene: "flat-lay-minimal",
        labelTR: "Minimal Flat Lay",
        labelEN: "Minimal Flat Lay",
        prompt: "overhead flat lay on clean white surface, clothing laid flat perfectly centered, soft natural window light, minimal e-commerce photography, no props",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "high-end baby brand editorial, pastel color palette, clean soft lighting, premium commercial baby apparel photography",
      },
    ],
  },
  {
    id: "jewelry",
    exampleImage: "/images/photo-sets/taki.png",
    labelTR: "Takı Fotoğraf Seti",
    labelEN: "Jewelry Photo Set",
    descriptionTR: "Takılar için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for jewelry.",
    scenes: [
      {
        scene: "studio-macro",
        labelTR: "Stüdyo Makro Hero",
        labelEN: "Studio Macro Hero",
        prompt: "pure white seamless background, macro studio lighting showing sparkle and shine, precise jewelry lighting setup with reflectors, high resolution luxury jewelry e-commerce photography",
      },
      {
        scene: "marble-flat-lay",
        labelTR: "Mermer Flat Lay",
        labelEN: "Marble Flat Lay",
        prompt: "white or light gray marble surface, jewelry placed naturally, soft natural window light from side, minimal elegant flat lay jewelry photography",
      },
      {
        scene: "gemstone-detail",
        labelTR: "Taş ve İşçilik Detayı",
        labelEN: "Gemstone & Craftsmanship",
        prompt: "extreme macro close-up of gemstone facets and metalwork, crystal sharp focus, precise jewelry macro studio lighting, white background, high resolution",
      },
      {
        scene: "velvet-display",
        labelTR: "Kadife Teşhir",
        labelEN: "Velvet Display",
        prompt: "dark navy or black velvet jewelry display surface, dramatic studio spotlight lighting, luxury jewelry brand photography, elegant dark background",
      },
      {
        scene: "lifestyle-props",
        labelTR: "Yaşam Tarzı — Çiçek",
        labelEN: "Lifestyle with Florals",
        prompt: "light marble or white wood surface with delicate dried flowers as soft background props, natural window light, elegant lifestyle jewelry photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "high-end luxury fashion editorial background, dramatic artistic directional lighting, sophisticated dark or neutral gradient backdrop, luxury jewelry magazine photography",
      },
    ],
  },
  {
    id: "bag",
    exampleImage: "/images/photo-sets/canta.png",
    labelTR: "Çanta Fotoğraf Seti",
    labelEN: "Bag Photo Set",
    descriptionTR: "Çantalar için 6 profesyonel sahne.",
    descriptionEN: "6 professional scenes for bags.",
    scenes: [
      {
        scene: "studio",
        labelTR: "Stüdyo Beyaz",
        labelEN: "Studio White",
        prompt: "pure white seamless background, bag standing upright centered, soft studio lighting, clean luxury fashion product photography, high resolution",
      },
      {
        scene: "marble-lifestyle",
        labelTR: "Mermer Yaşam Tarzı",
        labelEN: "Marble Lifestyle",
        prompt: "white marble surface background, bag placed naturally, soft natural window light, minimal elegant product styling, luxury fashion photography",
      },
      {
        scene: "material-detail",
        labelTR: "Deri ve Aksam Detayı",
        labelEN: "Material & Hardware Detail",
        prompt: "extreme close-up of bag material texture, stitching, zipper and hardware detail, sharp macro focus, soft studio lighting, leather or fabric detail photography",
      },
      {
        scene: "flat-lay",
        labelTR: "Aksesuvarlı Flat Lay",
        labelEN: "Styled Flat Lay",
        prompt: "overhead flat lay on clean white or light surface, bag as hero with minimal complementary accessories, natural light, fashion editorial flat lay photography",
      },
      {
        scene: "interior",
        labelTR: "İç Bölme",
        labelEN: "Interior View",
        prompt: "bag photographed open showing clean organized interior pockets and lining, studio lighting, white background, product detail photography",
      },
      {
        scene: "editorial",
        labelTR: "Editöryal",
        labelEN: "Editorial",
        prompt: "luxury fashion editorial background, dramatic directional lighting, dark or gradient neutral backdrop, high-end fashion magazine bag photography",
      },
    ],
  },
];

export function getPhotoSet(id) {
  return PHOTO_SETS.find((s) => s.id === id) ?? PHOTO_SETS[0];
}
