export const PHOTO_SETS = [
  {
    id: "general",
    exampleImage: "/images/photo-sets/genel.png",
    labelTR: "Ürün Fotoğraf Seti",
    labelEN: "Product Photo Set",
    descriptionTR: "Herhangi bir ürün için 6 profesyonel sahne: stüdyo hero, yaşam tarzı, detay, kullanım, alternatif açı ve editöryal.",
    descriptionEN: "6 professional scenes for any product: studio hero, lifestyle, detail, usage, alternative angle, editorial.",
    scenes: [
      { scene: "studio-hero", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio hero shot of {product} on pure white background, soft box studio lighting, clean e-commerce photography, high resolution" },
      { scene: "lifestyle", labelTR: "Yaşam Tarzı Bağlamı", labelEN: "Lifestyle Context",
        prompt: "{product} in a modern minimalist interior, natural light, lifestyle photography, warm tones, shallow depth of field" },
      { scene: "detail-closeup", labelTR: "Detay Yakın Çekim", labelEN: "Detail Closeup",
        prompt: "extreme close-up detail shot of {product}, sharp focus on texture and material, macro photography, professional studio lighting" },
      { scene: "usage-scene", labelTR: "Kullanım Sahnesi", labelEN: "Usage Scene",
        prompt: "{product} being used in a real-life setting, authentic lifestyle photography, editorial style, natural environment" },
      { scene: "alt-angle", labelTR: "Alternatif Açı", labelEN: "Alternative Angle",
        prompt: "{product} photographed from an alternative angle, creative composition, professional product photography, neutral background" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} in an elegant editorial style, high-end magazine photography, dramatic lighting, luxury aesthetic, professional commercial photo" },
    ],
  },
  {
    id: "armchair",
    exampleImage: "/images/photo-sets/koltuk-berjer.png",
    labelTR: "Koltuk & Berjer Fotoğraf Seti",
    labelEN: "Armchair & Bergère Photo Set",
    descriptionTR: "Koltuk ve berjerler için: zarif stüdyo, oturma odası ortamı, döşeme detayı, kullanım, alternatif açı ve editöryal.",
    descriptionEN: "For armchairs and bergères: elegant studio, living room, upholstery detail, usage, alternative angle, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Zarif Stüdyo", labelEN: "Elegant Studio",
        prompt: "professional studio photo of {product} armchair on clean white background, elegant studio lighting, furniture product photography, high resolution" },
      { scene: "living-room", labelTR: "Oturma Odası Ortamı", labelEN: "Living Room Setting",
        prompt: "{product} armchair in a beautifully designed modern living room, natural light, lifestyle interior photography, cozy ambiance" },
      { scene: "upholstery-detail", labelTR: "Döşeme Detay Yakın Çekimi", labelEN: "Upholstery Detail",
        prompt: "extreme close-up of {product} armchair fabric upholstery texture, detail shot, soft studio lighting, textile macro photography" },
      { scene: "usage", labelTR: "Kullanım Sahnesi", labelEN: "Usage Scene",
        prompt: "person relaxing comfortably in {product} armchair, cozy lifestyle scene, warm interior lighting, authentic living moment" },
      { scene: "alt-angle", labelTR: "Alternatif Açı", labelEN: "Alternative Angle",
        prompt: "{product} armchair photographed from a 45-degree side angle, showing full profile, clean neutral background, professional furniture photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} armchair in a high-end interior design editorial, architectural photography style, luxury magazine aesthetic, dramatic soft lighting" },
    ],
  },
  {
    id: "sofa-set",
    exampleImage: "/images/photo-sets/koltuk-takimi.png",
    labelTR: "Koltuk Takımı Fotoğraf Seti",
    labelEN: "Sofa Set Photo Set",
    descriptionTR: "3+2+1, köşe ve komple oturma grupları için: stüdyo düzeni, oturma odası, döşeme detayı, aile sahnesi, konfigürasyon ve editöryal.",
    descriptionEN: "For 3+2+1, corner and complete seating groups: studio layout, living room, upholstery detail, family scene, configuration, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Zarif Stüdyo Düzeni", labelEN: "Elegant Studio Layout",
        prompt: "professional studio photo of {product} sofa set arrangement on clean white background, elegant studio lighting, furniture product photography" },
      { scene: "living-room", labelTR: "Oturma Odası Ortamı", labelEN: "Living Room Setting",
        prompt: "{product} sofa set in a spacious modern living room, natural window light, full room staging, interior lifestyle photography" },
      { scene: "upholstery-detail", labelTR: "Döşeme Detayı", labelEN: "Upholstery Detail",
        prompt: "close-up detail of {product} sofa upholstery fabric and cushions, texture detail shot, professional studio lighting" },
      { scene: "family", labelTR: "Aile Sahnesi", labelEN: "Family Scene",
        prompt: "family sitting together on {product} sofa set, warm living room atmosphere, lifestyle photography, joyful home scene" },
      { scene: "configuration", labelTR: "Konfigürasyon Görünümü", labelEN: "Configuration View",
        prompt: "wide angle view of complete {product} sofa set configuration showing full layout, architectural product photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} sofa set in a luxury interior design editorial, high-end magazine photography, dramatic lighting, modern architecture" },
    ],
  },
  {
    id: "dining-set",
    exampleImage: "/images/photo-sets/yemek-masasi.png",
    labelTR: "Yemek Masası Takımı Fotoğraf Seti",
    labelEN: "Dining Table Set Photo Set",
    descriptionTR: "Yemek masası takımları için: stüdyo hero, yemek odası ortamı, sofra düzeni, detay, geniş açı ve editöryal.",
    descriptionEN: "For dining sets: studio hero, dining room, table setting, detail, wide angle, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} dining table set on clean white background, elegant studio lighting, furniture product photography" },
      { scene: "dining-room", labelTR: "Yemek Odası Ortamı", labelEN: "Dining Room Setting",
        prompt: "{product} dining table set in a beautifully designed dining room, natural light, interior lifestyle photography, elegant table styling" },
      { scene: "table-setting", labelTR: "Sofra Düzeni", labelEN: "Styled Table Setting",
        prompt: "{product} dining table elegantly set for dinner with plates and decorations, lifestyle photography, warm ambient lighting" },
      { scene: "detail", labelTR: "Ahşap Detay Yakın Çekim", labelEN: "Wood Detail Closeup",
        prompt: "close-up detail of {product} dining table wood grain surface and joinery craftsmanship, macro detail shot, professional lighting" },
      { scene: "alt-angle", labelTR: "Geniş Oda Görünümü", labelEN: "Wide Room View",
        prompt: "{product} dining table set from a wide room perspective, showing scale in space, architectural interior photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} dining set in high-end interior editorial, luxury lifestyle magazine photography, dramatic lighting, sophisticated styling" },
    ],
  },
  {
    id: "chair",
    exampleImage: "/images/photo-sets/sandalye.png",
    labelTR: "Sandalye Fotoğraf Seti",
    labelEN: "Chair Photo Set",
    descriptionTR: "Sandalyeler için: stüdyo hero, yaşam tarzı, malzeme detayı, kullanım sahnesi, çoklu görünüm ve editöryal.",
    descriptionEN: "For chairs: studio hero, lifestyle, material detail, usage scene, multiple view, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} chair on pure white background, soft studio lighting, clean furniture product photography" },
      { scene: "lifestyle", labelTR: "İç Mekan Yaşam Tarzı", labelEN: "Interior Lifestyle",
        prompt: "{product} chair in a modern interior setting, natural light, lifestyle photography, stylish home decor context" },
      { scene: "detail", labelTR: "Malzeme ve Aksam Detayı", labelEN: "Material & Hardware Detail",
        prompt: "close-up of {product} chair legs, seat and craftsmanship detail, material texture, macro product photography" },
      { scene: "usage", labelTR: "Kullanım Sahnesi", labelEN: "Usage Scene",
        prompt: "person sitting elegantly on {product} chair, authentic lifestyle scene, natural interior lighting" },
      { scene: "stack-alt", labelTR: "Çoklu / Alternatif Açı", labelEN: "Multiple / Alternative Angle",
        prompt: "{product} chairs arranged in a group or shown from alternative angle, creative composition, professional furniture photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} chair in editorial interior design setting, high-end magazine aesthetic, moody dramatic lighting, architectural photography" },
    ],
  },
  {
    id: "bed-frame",
    exampleImage: "/images/photo-sets/karyola.png",
    labelTR: "Karyola Fotoğraf Seti",
    labelEN: "Bed Frame Photo Set",
    descriptionTR: "Karyolalar için: stüdyo hero, yatak odası ortamı, başlık detayı, yaşam tarzı sahnesi, geniş açı ve editöryal.",
    descriptionEN: "For bed frames: studio hero, bedroom setting, headboard detail, lifestyle scene, wide angle, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} bed frame on clean white background, elegant studio lighting, furniture product photography" },
      { scene: "bedroom", labelTR: "Yatak Odası Ortamı", labelEN: "Bedroom Setting",
        prompt: "{product} bed frame in a beautifully styled bedroom, natural morning light, interior lifestyle photography, cozy bedding styling" },
      { scene: "headboard-detail", labelTR: "Başlık Detay Yakın Çekimi", labelEN: "Headboard Detail Closeup",
        prompt: "close-up detail of {product} bed headboard design and material, craftsmanship detail shot, soft studio lighting" },
      { scene: "usage", labelTR: "Yaşam Tarzı Sahnesi", labelEN: "Lifestyle Scene",
        prompt: "person reading or relaxing on {product} bed, morning lifestyle scene, natural bedroom lighting, cozy atmosphere" },
      { scene: "alt-angle", labelTR: "Ayak Ucundan Geniş Açı", labelEN: "Foot-of-Bed Wide Angle",
        prompt: "{product} bed frame from foot-of-bed perspective showing full room, architectural bedroom photography, wide angle" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} bed in luxury hotel-style editorial bedroom, high-end interior magazine photography, dramatic lighting, sophisticated staging" },
    ],
  },
  {
    id: "office-furniture",
    exampleImage: "/images/photo-sets/ofis-mobilyasi.png",
    labelTR: "Ofis Mobilyası Fotoğraf Seti",
    labelEN: "Office Furniture Photo Set",
    descriptionTR: "Ofis mobilyaları için: stüdyo hero, ofis ortamı, malzeme detayı, kullanım sahnesi, alternatif açı ve editöryal.",
    descriptionEN: "For office furniture: studio hero, office setting, material detail, usage scene, alternative angle, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} office furniture on clean white background, crisp studio lighting, corporate product photography" },
      { scene: "office", labelTR: "Ofis Ortamı", labelEN: "Professional Office Setting",
        prompt: "{product} office furniture in a modern professional office space, natural light, workspace lifestyle photography, productive atmosphere" },
      { scene: "detail", labelTR: "Yüzey ve Aksam Detayı", labelEN: "Surface & Hardware Detail",
        prompt: "close-up detail of {product} office furniture surface finish and hardware, material texture shot, professional lighting" },
      { scene: "usage", labelTR: "Çalışma Sahnesi", labelEN: "Work Scene",
        prompt: "professional working at {product} office furniture, productive workspace scene, natural office lighting" },
      { scene: "alt-angle", labelTR: "Alternatif Açı", labelEN: "Alternative Angle",
        prompt: "{product} office furniture from alternative perspective, creative workspace composition, professional commercial photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} office furniture in a high-end executive interior editorial, architectural office photography, premium workspace aesthetic" },
    ],
  },
  {
    id: "floor-cushion",
    exampleImage: "/images/photo-sets/minder.png",
    labelTR: "Minder Fotoğraf Seti",
    labelEN: "Floor Cushion Photo Set",
    descriptionTR: "Minderler için: stüdyo hero, yaşam tarzı, kumaş detayı, kullanım sahnesi, grup çekim ve editöryal.",
    descriptionEN: "For floor cushions: studio hero, lifestyle, fabric detail, usage scene, group arrangement, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} floor cushion on pure white background, soft studio lighting, clean product photography" },
      { scene: "lifestyle", labelTR: "Yaşam Tarzı Ortamı", labelEN: "Lifestyle Setting",
        prompt: "{product} floor cushion in a bohemian or minimalist living room, natural light, lifestyle interior photography, cozy floor seating" },
      { scene: "fabric-detail", labelTR: "Kumaş Detay Yakın Çekimi", labelEN: "Fabric Detail Closeup",
        prompt: "close-up macro of {product} cushion fabric texture, stitching and material quality detail, soft product photography" },
      { scene: "usage", labelTR: "Kullanım Sahnesi", labelEN: "Usage Scene",
        prompt: "person sitting relaxed on {product} floor cushion, cozy meditation or reading nook, warm natural lighting" },
      { scene: "group", labelTR: "Grup Düzenleme", labelEN: "Group Arrangement",
        prompt: "multiple {product} floor cushions styled together in a living space, home decor arrangement, editorial interior photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} floor cushion in boho chic interior editorial styling, home decor magazine photography, warm dramatic lighting" },
    ],
  },
  {
    id: "throw-pillow",
    exampleImage: "/images/photo-sets/kirlent.png",
    labelTR: "Kırlent Fotoğraf Seti",
    labelEN: "Throw Pillow Photo Set",
    descriptionTR: "Kırlentler için: stüdyo hero, koltukta stilize, kumaş detayı, yatakta stilize, kırlent grubu ve editöryal.",
    descriptionEN: "For throw pillows: studio hero, styled on sofa, fabric detail, styled on bed, pillow group, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} throw pillow on clean white background, soft studio lighting, home textile product photography" },
      { scene: "sofa-styled", labelTR: "Koltuk Üzerinde Stilize", labelEN: "Styled on Sofa",
        prompt: "{product} throw pillow beautifully styled on a modern sofa, interior lifestyle photography, natural light, home decor styling" },
      { scene: "fabric-detail", labelTR: "Kumaş ve Desen Detayı", labelEN: "Fabric & Pattern Detail",
        prompt: "extreme close-up of {product} throw pillow fabric texture, embroidery or pattern detail, macro textile photography" },
      { scene: "bed-styled", labelTR: "Yatak Üzerinde Stilize", labelEN: "Styled on Bed",
        prompt: "{product} throw pillow on a luxuriously made bed, elegant bedroom styling, soft morning light, interior photography" },
      { scene: "group", labelTR: "Kırlent Grubu", labelEN: "Pillow Group Arrangement",
        prompt: "arrangement of {product} throw pillows styled complementarily on couch, home decor photography, editorial styling" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} throw pillow in a high-end interior editorial, luxury home decor magazine photography, dramatic lighting" },
    ],
  },
  {
    id: "curtain",
    exampleImage: "/images/photo-sets/perde.png",
    labelTR: "Perde Fotoğraf Seti",
    labelEN: "Curtain Photo Set",
    descriptionTR: "Perdeler için: stüdyo hero, pencere ortamı, kumaş detayı, oda bağlamı, desen detayı ve editöryal.",
    descriptionEN: "For curtains: studio hero, window setting, fabric detail, room context, pattern detail, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} curtain hung and draped, clean studio lighting showing full fall and fabric, textile product photography" },
      { scene: "window", labelTR: "Pencere Ortamı", labelEN: "Window Setting",
        prompt: "{product} curtain hanging elegantly at a window, natural daylight filtering through, interior lifestyle photography, airy atmosphere" },
      { scene: "fabric-detail", labelTR: "Kumaş Dökümü Detayı", labelEN: "Fabric Drape Detail",
        prompt: "close-up detail of {product} curtain fabric drape and texture, light filtering through material, macro textile photography" },
      { scene: "room-context", labelTR: "Oda Bağlamı", labelEN: "Full Room Context",
        prompt: "{product} curtain as part of a fully styled living room, showing how it frames the space, interior design photography" },
      { scene: "pattern-detail", labelTR: "Desen ve Nakış Detayı", labelEN: "Pattern & Embroidery Detail",
        prompt: "close-up of {product} curtain pattern or embroidery design, flat detail shot, professional textile photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} curtain in a luxury interior editorial, dramatic backlit window styling, high-end home magazine photography" },
    ],
  },
  {
    id: "tablecloth",
    exampleImage: "/images/photo-sets/masa-ortusu.png",
    labelTR: "Masa Örtüsü Fotoğraf Seti",
    labelEN: "Tablecloth Photo Set",
    descriptionTR: "Masa örtüleri için: stüdyo hero, sofra düzeni, kumaş detayı, açık hava, flat lay ve editöryal.",
    descriptionEN: "For tablecloths: studio hero, table setting, fabric detail, outdoor, flat lay, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} tablecloth on a table, clean studio lighting, textile product photography, full spread view" },
      { scene: "table-setting", labelTR: "Sofra Düzeni", labelEN: "Styled Table Setting",
        prompt: "{product} tablecloth on an elegantly set dining table with tableware, lifestyle photography, warm ambient lighting" },
      { scene: "fabric-detail", labelTR: "Kumaş Doku Detayı", labelEN: "Fabric Texture Detail",
        prompt: "close-up macro of {product} tablecloth fabric texture, weave pattern and hem detail, soft studio lighting" },
      { scene: "outdoor", labelTR: "Açık Hava Yemek", labelEN: "Outdoor Dining",
        prompt: "{product} tablecloth on an outdoor garden or terrace table, natural sunlight, lifestyle outdoor dining photography" },
      { scene: "flat-lay", labelTR: "Flat Lay Editöryal", labelEN: "Flat Lay Editorial",
        prompt: "overhead flat lay of {product} tablecloth with decorative props on surface, editorial home decor photography, clean composition" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} tablecloth in a high-end interior editorial, luxury dining scene, dramatic candlelit atmosphere, magazine photography" },
    ],
  },
  {
    id: "blanket",
    exampleImage: "/images/photo-sets/battaniye.png",
    labelTR: "Battaniye Fotoğraf Seti",
    labelEN: "Blanket Photo Set",
    descriptionTR: "Battaniyeler için: stüdyo hero, koltukta rahatlama, kumaş detayı, kullanım sahnesi, yatak üzerinde ve editöryal.",
    descriptionEN: "For blankets: studio hero, cozy sofa, fabric detail, usage scene, on bed, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} blanket neatly folded or draped on white background, soft studio lighting, textile photography" },
      { scene: "cozy-sofa", labelTR: "Koltukta Rahatlama", labelEN: "Cozy Sofa Scene",
        prompt: "{product} blanket draped over a sofa, cozy interior scene, warm natural light, lifestyle home photography" },
      { scene: "fabric-detail", labelTR: "Kumaş Doku Detayı", labelEN: "Fabric Texture Detail",
        prompt: "extreme close-up of {product} blanket fabric weave, texture and softness detail, macro textile photography, warm lighting" },
      { scene: "usage", labelTR: "Sarınma Sahnesi", labelEN: "Wrapped Usage Scene",
        prompt: "person wrapped in {product} blanket on a cozy sofa, warm lifestyle scene, autumn atmosphere, natural lighting" },
      { scene: "bed", labelTR: "Yatak Ayak Ucunda", labelEN: "At Foot of Bed",
        prompt: "{product} blanket folded neatly at foot of bed, elegant bedroom styling, morning light, interior photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} blanket in luxury interior editorial, dramatic moody winter atmosphere, high-end home magazine photography" },
    ],
  },
  {
    id: "bedspread",
    exampleImage: "/images/photo-sets/yatak-ortusu.png",
    labelTR: "Yatak Örtüsü & Pike Fotoğraf Seti",
    labelEN: "Bedspread & Quilt Photo Set",
    descriptionTR: "Yatak örtüsü ve pikeler için: stüdyo hero, yatak odası ortamı, nakış detayı, yastıklarla stilize, flat lay ve editöryal.",
    descriptionEN: "For bedspreads and quilts: studio hero, bedroom setting, quilting detail, styled with pillows, flat lay, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} bedspread on a neatly made bed, clean studio lighting, home textile product photography" },
      { scene: "bedroom", labelTR: "Yatak Odası Ortamı", labelEN: "Bedroom Setting",
        prompt: "{product} bedspread on a beautifully styled bed in a bright bedroom, natural light, interior lifestyle photography" },
      { scene: "quilt-detail", labelTR: "Nakış ve Doku Detayı", labelEN: "Quilting & Texture Detail",
        prompt: "close-up of {product} bedspread quilting pattern and fabric texture, detail macro photography, soft diffused lighting" },
      { scene: "pillow-styled", labelTR: "Yastıklarla Komple Stilize", labelEN: "Fully Styled with Pillows",
        prompt: "{product} bedspread on bed styled with matching pillows and cushions, complete bedroom styling, interior design photography" },
      { scene: "flat-lay", labelTR: "Detay Flat Lay", labelEN: "Detail Flat Lay",
        prompt: "overhead flat lay close-up of {product} bedspread texture and pattern, editorial textile photography, clean composition" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} bedspread in luxury hotel-style editorial bedroom, high-end interior magazine photography, dramatic soft lighting" },
    ],
  },
  {
    id: "baby-clothing",
    exampleImage: "/images/photo-sets/bebek-kiyafeti.png",
    labelTR: "Bebek Kıyafeti Fotoğraf Seti",
    labelEN: "Baby Clothing Photo Set",
    descriptionTR: "Bebek kıyafetleri için: stüdyo hero, flat lay stilize, kumaş detayı, bebek üzerinde, askıda çekim ve editöryal.",
    descriptionEN: "For baby clothing: studio hero, styled flat lay, fabric detail, on baby, on hanger, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} baby clothing on white background, soft studio lighting, clean e-commerce apparel photography" },
      { scene: "flat-lay", labelTR: "Aksesuvarlı Flat Lay", labelEN: "Accessorized Flat Lay",
        prompt: "overhead flat lay of {product} baby clothing styled with cute props like toys and shoes, pastel background, baby lifestyle photography" },
      { scene: "fabric-detail", labelTR: "Kumaş Yumuşaklık Detayı", labelEN: "Fabric Softness Detail",
        prompt: "close-up of {product} baby clothing fabric texture, softness and stitching quality, macro textile photography" },
      { scene: "on-baby", labelTR: "Bebek Üzerinde", labelEN: "Worn by Baby",
        prompt: "adorable baby wearing {product} baby clothing, natural light, authentic baby lifestyle photography, joyful moment" },
      { scene: "hanger", labelTR: "Askıda Çekim", labelEN: "On Decorative Hanger",
        prompt: "{product} baby clothing on a small decorative hanger in a nursery setting, soft natural light, product photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} baby clothing in a high-end baby brand editorial, pastel color palette, professional commercial baby photography" },
    ],
  },
  {
    id: "jewelry",
    exampleImage: "/images/photo-sets/taki.png",
    labelTR: "Takı Fotoğraf Seti",
    labelEN: "Jewelry Photo Set",
    descriptionTR: "Takılar için: stüdyo makro, yaşam tarzı flat lay, mücevher detayı, takılmış halde, lüks yüzeyde ve editöryal.",
    descriptionEN: "For jewelry: studio macro, lifestyle flat lay, gemstone detail, worn, luxury surface, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Makro Hero", labelEN: "Studio Macro Hero",
        prompt: "professional macro studio photo of {product} jewelry on pure white background, precise studio lighting showing sparkle and detail, luxury jewelry photography" },
      { scene: "lifestyle", labelTR: "Yaşam Tarzı Flat Lay", labelEN: "Lifestyle Flat Lay",
        prompt: "{product} jewelry on a marble surface with flowers and luxury props, lifestyle product photography, elegant flat lay, soft natural lighting" },
      { scene: "gemstone-detail", labelTR: "Taş ve Maden Detayı", labelEN: "Gemstone & Metalwork Detail",
        prompt: "extreme macro close-up of {product} jewelry gemstones and metalwork, crystal clarity, professional jewelry macro photography" },
      { scene: "worn", labelTR: "Takılmış Halde", labelEN: "Worn on Model",
        prompt: "{product} jewelry worn elegantly, lifestyle portrait photography, natural or studio lighting, showcasing the piece beautifully" },
      { scene: "luxury-surface", labelTR: "Kadife / Mermer Üzerinde", labelEN: "On Velvet / Marble",
        prompt: "{product} jewelry on dark velvet or luxurious marble surface, dramatic studio lighting, high-end jewelry brand photography" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} jewelry in a luxury fashion editorial, high-end magazine photography, dramatic artistic lighting, sophisticated composition" },
    ],
  },
  {
    id: "bag",
    exampleImage: "/images/photo-sets/canta.png",
    labelTR: "Çanta Fotoğraf Seti",
    labelEN: "Bag Photo Set",
    descriptionTR: "Çantalar için: stüdyo hero, yaşam tarzı, deri/malzeme detayı, flat lay, iç görünüm ve editöryal.",
    descriptionEN: "For bags: studio hero, lifestyle, leather/material detail, flat lay, interior view, editorial.",
    scenes: [
      { scene: "studio", labelTR: "Stüdyo Hero", labelEN: "Studio Hero",
        prompt: "professional studio photo of {product} bag on pure white background, clean studio lighting, luxury fashion product photography" },
      { scene: "lifestyle", labelTR: "Yaşam Tarzı Taşıma", labelEN: "Lifestyle Carry",
        prompt: "{product} bag held or carried in a stylish urban or outdoor setting, fashion lifestyle photography, natural light" },
      { scene: "material-detail", labelTR: "Deri ve Aksam Detayı", labelEN: "Leather & Hardware Detail",
        prompt: "close-up detail of {product} bag leather or material texture, hardware, stitching and craftsmanship, macro product photography" },
      { scene: "flat-lay", labelTR: "Aksesuvarlı Flat Lay", labelEN: "Styled Flat Lay",
        prompt: "overhead flat lay of {product} bag with complementary accessories on a clean surface, fashion editorial photography, styled composition" },
      { scene: "interior", labelTR: "İç Bölme Görünümü", labelEN: "Interior Compartment View",
        prompt: "professional photo of {product} bag open showing interior pockets and organization, product detail photography, studio lighting" },
      { scene: "editorial", labelTR: "Editöryal Stil", labelEN: "Editorial Style",
        prompt: "{product} bag in a high-end fashion editorial, luxury brand photography, dramatic lighting, sophisticated fashion magazine aesthetic" },
    ],
  },
];

export function getPhotoSet(id) {
  return PHOTO_SETS.find((s) => s.id === id) ?? PHOTO_SETS[0];
}
