name = "snap6-ai-photo-studio"
client_id = "1aa948957f2ea5289d54b09f9064f8f6"
application_url = "https://app.rankavio.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_files,read_files"

[auth]
redirect_urls = [
  "https://app.rankavio.com/auth/callback",
  "https://app.rankavio.com/auth/shopify/callback",
  "https://app.rankavio.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks"

[pos]
embedded = false
