name = "snap6-ai-photo-studio"
client_id = "1aa948957f2ea5289d54b09f9064f8f6"
application_url = "https://app.rankavio.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_files,read_files"

[auth]
redirect_urls = [
  "https://app.rankavio.com/auth/callback",
  "https://app.rankavio.com/auth/shopify/callback",
  "https://app.rankavio.com/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://app.rankavio.com/webhooks"
  customer_data_request_url = "https://app.rankavio.com/webhooks"
  shop_deletion_url = "https://app.rankavio.com/webhooks"

[pos]
embedded = false
