api_version = "2025-10"
uid = "f920ce53-953a-c24b-4242-b039787f5ff680b3be80"

[[extensions]]
name = "Snap6 — 6 Sahne Üret"
handle = "product-photo-studio"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/BlockExtension.jsx"
  target = "admin.product-details.block.render"
